# Generated by Django 4.2.15 on 2025-03-28 14:22

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0279_discount_event_date_from_discount_event_date_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkinlist_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
