# Generated by Django 4.2.20 on 2025-04-16 20:23

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0280_event_is_voting_question_unique_subevent_crowd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_form',
            field=models.BooleanField(default=False),
        ),
    ]
