# Generated by Django 4.2.20 on 2025-07-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0281_event_is_form_subevent_crowd'),
        ('pretixbase', '0283_taxrule_default_taxrule_backfill'),
    ]

    operations = [
    ]
